# Generated by Django 6.0.6 on 2026-06-25 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessment.academicyear'),
        ),
    ]
