# Generated by Django 6.0.6 on 2026-06-25 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessment_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=10)),
                ('full_marks', models.IntegerField(default=25)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.subject')),
            ],
        ),
    ]
