# Generated by Django 6.0.6 on 2026-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_classsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='full_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(default='10', max_length=10),
        ),
    ]
