# Generated by Django 6.0.6 on 2026-06-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_subject_full_marks_subject_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='classwork',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='homework',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='mcqs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='viva',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
